server:
  port: 8101

eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_resource_planner_db
    username: chemical
    password: chemical
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/chemical-platform
  kafka:
    bootstrap-servers: localhost:9092
